# -*- coding: utf-8 -*-
import os

path = r'c:\Users\Saakshi18\OneDrive\Desktop\Saakshi\Flutter\lib\l10n\auth_strings.dart'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

translations = {
    'en': {
        'serviceCompletionTitle': "Service Completion",
        'serviceCompletedTitle': "Service Completed!",
        'serviceCompletedSubtitle': "Thank you! Your service has been completed successfully.",
        'serviceDetailsTitle': "Service Details",
        'dateTimeLabel': "Date & Time",
        'addressLabel': "Address",
        'totalAmountLabel': "Total Cost",
        'viewBreakdownBtn': "View Breakdown",
        'beforeAfterPhotosTitle': "Work Photos (Before / After)",
        'beforeTag': "Before",
        'afterTag': "After",
        'proceedToPaymentBtn': "Proceed to Payment ➔",
        'rateExperienceBtn': "Rate Experience",
        'downloadInvoiceBtn': "Download Invoice",
        'billSummaryTitle': "Bill Summary",
        'baseAmountLabel': "Base Amount",
        'materialsCostLabel': "Materials Cost",
        'serviceFeeLabel': "Service Fee",
        'discountLabel': "Discount",
        'paymentInfoTitle': "Payment Info",
        'paymentSuccessfulBadge': "Payment Successful",
        'paymentPendingBadge': "Payment Pending",
        'txnIdLabel': "Txn ID",
        'dateLabel': "Date",
        'materialsUsedTitle': "Materials Used",
        'materialsIncludedNote': "Included in materials cost.",
        'serviceDurationTitle': "Service Duration",
        'totalDurationLabel': "Total Duration",
        'startTimeLabel': "Start",
        'endTimeLabel': "End",
        'rebookTileTitle': "Book Again",
        'rebookTileDesc': "Need this service again? Rebook in one tap.",
        'rebookWithWorkerDesc': "Need similar service again? Book again with Rahul Sharma.",
        'invoiceTileTitle': "Invoice / Receipt",
        'invoiceTileDesc': "Download PDF invoice and share.",
        'helpTileTitle': "Need Help?",
        'helpTileDesc': "If you have any issues, we are ready to help.",
        'contactBtn': "Contact Support",
        'serviceWarrantyTitle': "Service Warranty",
        'serviceWarrantyDesc': "We provide a 7-day warranty for our service.",
        'moreInfoBtn': "More Info",
        'shareServiceTitle': "Share Service",
        'shareServiceDesc': "Recommend SahayogSeva to your friends.",
        'shareBtn': "Share",
        'afterServiceTitle': "After Service",
        'workSummaryTitle': "Work Summary",
        'problemLabel': "Problem",
        'workDoneLabel': "Work Done",
        'actualDurationLabel': "Actual Time Taken",
        'completionTimeLabel': "Service Completion Time",
        'paymentDetailsTitle': "Payment Details",
        'paymentMethodLabel': "Payment Method",
        'paymentStatusLabel': "Payment Status",
        'invoiceNumberLabel': "Invoice Number",
        'rateAndFeedbackBtn': "Give Rating & Feedback",
        'rateWorkerTitle': "Give Rating",
        'howWasExperience': "How was your experience?",
        'rateWorkerPrompt': "Rate {name}",
        'writeFeedbackHint': "Write your feedback... (minimum 10 words)",
        'submitRatingBtn': "Submit Rating",
        'step15ProceedToPayment': "Proceed to Payment ➔",
        'paymentModalTitle': "Make Payment",
        'payNowBtn': "Pay Now",
        'ratingSubmittedSuccess': "Thank you! Rating submitted successfully.",
        'ratingStar1': "Poor",
        'ratingStar2': "Fair",
        'ratingStar3': "Good",
        'ratingStar4': "Very Good",
        'ratingStar5': "Excellent",
        'unitNos': "nos.",
        'paymentProcessing': "Processing payment...",
        'ratingSubmitting': "Submitting rating...",
        'invoiceDownloading': "Downloading invoice PDF...",
        'invoiceDownloaded': "Invoice downloaded successfully!",
        'warrantyModalTitle': "7-Day Service Warranty Policy",
        'warrantyModalContent': "SahayogSeva guarantees high-quality workmanship for 7 days. If the issue reoccurs within 7 days, our cooperative worker will resolve it free of charge.",
        'sampleProblemDesc': "Water was leaking from the tap.",
        'sampleWorkDoneDesc': "Joint repaired and rubber washer replaced.",
    },
    'hi': {
        'serviceCompletionTitle': "सेवा पूर्णता",
        'serviceCompletedTitle': "सेवा पूर्ण हुई!",
        'serviceCompletedSubtitle': "धन्यवाद! आपकी सेवा सफलतापूर्वक पूरी हो गई है।",
        'serviceDetailsTitle': "सेवा विवरण",
        'dateTimeLabel': "दिनांक और समय",
        'addressLabel': "पता",
        'totalAmountLabel': "कुल खर्च",
        'viewBreakdownBtn': "विवरण देखें",
        'beforeAfterPhotosTitle': "काम की तस्वीरें (पहले / बाद में)",
        'beforeTag': "पहले",
        'afterTag': "बाद में",
        'proceedToPaymentBtn': "भुगतान करें ➔",
        'rateExperienceBtn': "अनुभव को रेट करें",
        'downloadInvoiceBtn': "रसीद डाउनलोड करें",
        'billSummaryTitle': "बिल सारांश",
        'baseAmountLabel': "मूल राशि",
        'materialsCostLabel': "सामग्री खर्च",
        'serviceFeeLabel': "सेवा शुल्क",
        'discountLabel': "छूट",
        'paymentInfoTitle': "भुगतान जानकारी",
        'paymentSuccessfulBadge': "भुगतान सफल",
        'paymentPendingBadge': "भुगतान लंबित",
        'txnIdLabel': "लेन-देन आईडी",
        'dateLabel': "दिनांक",
        'materialsUsedTitle': "इस्तेमाल की गई सामग्री",
        'materialsIncludedNote': "सामग्री खर्च में शामिल है।",
        'serviceDurationTitle': "सेवा अवधि",
        'totalDurationLabel': "कुल अवधि",
        'startTimeLabel': "शुरुआत",
        'endTimeLabel': "समाप्ति",
        'rebookTileTitle': "फिर से बुक करें",
        'rebookTileDesc': "क्या यह सेवा फिर से चाहिए? एक टैप में बुक करें।",
        'rebookWithWorkerDesc': "फिर से ऐसी सेवा चाहिए? राहुल शर्मा के साथ फिर से बुक करें।",
        'invoiceTileTitle': "चालान / रसीद",
        'invoiceTileDesc': "PDF रसीद डाउनलोड करें और शेयर करें।",
        'helpTileTitle': "मदद चाहिए?",
        'helpTileDesc': "यदि कोई समस्या है तो हम मदद के लिए तैयार हैं।",
        'contactBtn': "संपर्क करें",
        'serviceWarrantyTitle': "सेवा गारंटी",
        'serviceWarrantyDesc': "हम अपनी सेवा के लिए 7 दिनों की गारंटी देते हैं।",
        'moreInfoBtn': "अधिक जानकारी",
        'shareServiceTitle': "सेवा साझा करें",
        'shareServiceDesc': "अपने दोस्तों को SahayogSeva की सिफारिश करें।",
        'shareBtn': "साझा करें",
        'afterServiceTitle': "सेवा के बाद",
        'workSummaryTitle': "काम का सारांश",
        'problemLabel': "समस्या",
        'workDoneLabel': "किया गया काम",
        'actualDurationLabel': "वास्तविक लगा समय",
        'completionTimeLabel': "सेवा पूर्ण समय",
        'paymentDetailsTitle': "भुगतान विवरण",
        'paymentMethodLabel': "भुगतान विधि",
        'paymentStatusLabel': "भुगतान स्थिति",
        'invoiceNumberLabel': "रसीद संख्या",
        'rateAndFeedbackBtn': "रेटिंग और फीडबैक दें",
        'rateWorkerTitle': "रेटिंग दें",
        'howWasExperience': "आपका अनुभव कैसा था?",
        'rateWorkerPrompt': "{name} को रेट करें",
        'writeFeedbackHint': "अपनी प्रतिक्रिया लिखें... (न्यूनतम 10 शब्द)",
        'submitRatingBtn': "सबमिट करें",
        'step15ProceedToPayment': "भुगतान करें ➔",
        'paymentModalTitle': "भुगतान करें",
        'payNowBtn': "अभी भुगतान करें",
        'ratingSubmittedSuccess': "धन्यवाद! आपकी रेटिंग सफलतापूर्वक दर्ज हो गई।",
        'ratingStar1': "खराब",
        'ratingStar2': "ठीक-ठाक",
        'ratingStar3': "अच्छा",
        'ratingStar4': "बहुत अच्छा",
        'ratingStar5': "उत्कृष्ट",
        'unitNos': "नग",
        'paymentProcessing': "भुगतान प्रक्रिया जारी है...",
        'ratingSubmitting': "रेटिंग सबमिट की जा रही है...",
        'invoiceDownloading': "PDF रसीद डाउनलोड हो रही है...",
        'invoiceDownloaded': "रसीद सफलतापूर्वक डाउनलोड हो गई!",
        'warrantyModalTitle': "7-दिवसीय सेवा गारंटी नीति",
        'warrantyModalContent': "SahayogSeva 7 दिनों के लिए काम की उच्च गुणवत्ता की गारंटी देती है। यदि समस्या पुनः होती है तो सहकारी कामगार इसे निःशुल्क ठीक करेंगे।",
        'sampleProblemDesc': "नल से पानी टपक रहा था।",
        'sampleWorkDoneDesc': "जॉइंट रिपेयर किया और रबर वॉशर बदला।",
    },
    'mr': {
        'serviceCompletionTitle': "सेवा पूर्णता",
        'serviceCompletedTitle': "सेवा पूर्ण झाली!",
        'serviceCompletedSubtitle': "धन्यवाद! आपली सेवा यशस्वीरीत्या पूर्ण झाली.",
        'serviceDetailsTitle': "सेवा तपशील",
        'dateTimeLabel': "दिनांक व वेळ",
        'addressLabel': "पत्ता",
        'totalAmountLabel': "एकूण खर्च",
        'viewBreakdownBtn': "तपशील पहा",
        'beforeAfterPhotosTitle': "कामाचे फोटो (Before / After)",
        'beforeTag': "Before",
        'afterTag': "After",
        'proceedToPaymentBtn': "पेमेंट करा ➔",
        'rateExperienceBtn': "अनुभव रेटिंग द्या",
        'downloadInvoiceBtn': "पावती डाउनलोड करा",
        'billSummaryTitle': "देयक सारांश",
        'baseAmountLabel': "मूळ रक्कम",
        'materialsCostLabel': "साहित्य खर्च",
        'serviceFeeLabel': "सेवा शुल्क",
        'discountLabel': "सवलत",
        'paymentInfoTitle': "पेमेंट माहिती",
        'paymentSuccessfulBadge': "पेमेंट यशस्वी",
        'paymentPendingBadge': "पेमेंट प्रलंबित",
        'txnIdLabel': "Txn ID",
        'dateLabel': "दिनांक",
        'materialsUsedTitle': "साहित्य वापरले",
        'materialsIncludedNote': "साहित्य खर्चात समाविष्ट आहे.",
        'serviceDurationTitle': "सेवा कालावधी",
        'totalDurationLabel': "एकूण कालावधी",
        'startTimeLabel': "सुरुवात",
        'endTimeLabel': "समाप्त",
        'rebookTileTitle': "पुन्हा बुक करा",
        'rebookTileDesc': "हीच सेवा पुन्हा हवी आहे? एका टॅपवर पुन्हा बुक करा.",
        'rebookWithWorkerDesc': "पुन्हा अशीच सेवा हवी आहे? राहुल शर्मा यांच्यासोबत पुन्हा बुक करा.",
        'invoiceTileTitle': "इन्व्हॉईस / पावती",
        'invoiceTileDesc': "PDF पावती डाउनलोड करा आणि शेअर करा.",
        'helpTileTitle': "मदत हवी आहे?",
        'helpTileDesc': "काही समस्या असल्यास आम्ही मदतीस तयार आहोत.",
        'contactBtn': "संपर्क करा",
        'serviceWarrantyTitle': "सेवा हमी",
        'serviceWarrantyDesc': "आम्ही आमच्या सेवेसाठी 7 दिवसांची हमी देतो.",
        'moreInfoBtn': "अधिक माहिती",
        'shareServiceTitle': "सेवा शेअर करा",
        'shareServiceDesc': "आपल्या मित्रांना SahayogSeva ची शिफारस करा.",
        'shareBtn': "शेअर करा",
        'afterServiceTitle': "सेवा नंतर",
        'workSummaryTitle': "कामाचा सारांश",
        'problemLabel': "समस्या",
        'workDoneLabel': "केलेले काम",
        'actualDurationLabel': "खरी लागलेला वेळ",
        'completionTimeLabel': "सेवा पूर्ण वेळ",
        'paymentDetailsTitle': "पेमेंट तपशील",
        'paymentMethodLabel': "पेमेंट पद्धत",
        'paymentStatusLabel': "पेमेंट स्थिती",
        'invoiceNumberLabel': "पावती क्रमांक",
        'rateAndFeedbackBtn': "रेटिंग आणि अभिप्राय द्या",
        'rateWorkerTitle': "रेटिंग द्या",
        'howWasExperience': "आपला अनुभव कसा होता?",
        'rateWorkerPrompt': "{name} यांना रेटिंग द्या.",
        'writeFeedbackHint': "आपला अभिप्राय लिहा... (किमान 10 शब्द)",
        'submitRatingBtn': "सबमिट करा",
        'step15ProceedToPayment': "पेमेंट करा ➔",
        'paymentModalTitle': "पेमेंट करा",
        'payNowBtn': "आता पेमेंट करा",
        'ratingSubmittedSuccess': "धन्यवाद! रेटिंग यशस्वीरीत्या सबमिट झाली.",
        'ratingStar1': "असमाधानकारक",
        'ratingStar2': "साधारण",
        'ratingStar3': "चांगले",
        'ratingStar4': "उत्कृष्ट",
        'ratingStar5': "अतिउत्कृष्ट",
        'unitNos': "नग",
        'paymentProcessing': "पेमेंट प्रक्रिया सुरू आहे...",
        'ratingSubmitting': "रेटिंग सबमिट होत आहे...",
        'invoiceDownloading': "PDF पावती डाउनलोड होत आहे...",
        'invoiceDownloaded': "पावती यशस्वीरित्या डाउनलोड झाली!",
        'warrantyModalTitle': "७ दिवसांची सेवा हमी धोरण",
        'warrantyModalContent': "सहयोगसेवा ७ दिवसांच्या कामाच्या हमीची खात्री देते. जर ७ दिवसांत समस्या पुन्हा उद्भवल्यास आमचे सहकारी कामगार ती मोफत दुरुस्त करतील.",
        'sampleProblemDesc': "नळातून पाणी गळत होते.",
        'sampleWorkDoneDesc': "जॉइंट रिपेअर आणि वॉशर बदलले.",
    },
    'gu': {
        'serviceCompletionTitle': "સેવા પૂર્ણતા",
        'serviceCompletedTitle': "સેવા પૂર્ણ થઈ!",
        'serviceCompletedSubtitle': "આભાર! તમારી સેવા સફળતાપૂર્વક પૂર્ણ થઈ ગઈ છે.",
        'serviceDetailsTitle': "સેવા વિગતો",
        'dateTimeLabel': "તારીખ અને સમય",
        'addressLabel': "સરનામું",
        'totalAmountLabel': "કુલ ખર્ચ",
        'viewBreakdownBtn': "વિગતો જુઓ",
        'beforeAfterPhotosTitle': "કામના ફોટા (પહેલા / પછી)",
        'beforeTag': "પહેલા",
        'afterTag': "પછી",
        'proceedToPaymentBtn': "ચુકવણી કરો ➔",
        'rateExperienceBtn': "અનુભવને રેટ કરો",
        'downloadInvoiceBtn': "રસીદ ડાઉનલોડ કરો",
        'billSummaryTitle': "બિલ સારાંશ",
        'baseAmountLabel': "મૂળ રકમ",
        'materialsCostLabel': "સામગ્રી ખર્ચ",
        'serviceFeeLabel': "સેવા શુલ્ક",
        'discountLabel': "ડિસ્કાઉન્ટ",
        'paymentInfoTitle': "ચુકવણી વિગતો",
        'paymentSuccessfulBadge': "ચુકવણી સફળ",
        'paymentPendingBadge': "ચુકવણી બાકી",
        'txnIdLabel': "ટ્રાન્ઝેક્શન આઈડી",
        'dateLabel': "તારીખ",
        'materialsUsedTitle': "વપરાયેલી સામગ્રી",
        'materialsIncludedNote': "સામગ્રી ખર્ચમાં શામેલ છે.",
        'serviceDurationTitle': "સેવા સમયગાળો",
        'totalDurationLabel': "કુલ સમય",
        'startTimeLabel': "શરૂઆત",
        'endTimeLabel': "સમાપ્તિ",
        'rebookTileTitle': "ફરીથી બુક કરો",
        'rebookTileDesc': "આ સેવા ફરીથી જોઈએ છે? એક ટૅપમાં ફરી બુક કરો.",
        'rebookWithWorkerDesc': "ફરીથી આ સેવા જોઈએ છે? રાહુલ શર્મા સાથે ફરી બુક કરો.",
        'invoiceTileTitle': "ચલણ / રસીદ",
        'invoiceTileDesc': "PDF રસીદ ડાઉનલોડ કરો અને શેર કરો.",
        'helpTileTitle': "મદદ જોઈએ છે?",
        'helpTileDesc': "જો કોઈ સમસ્યા હોય તો અમે મદદ માટે તૈયાર છીએ.",
        'contactBtn': "સંપર્ક કરો",
        'serviceWarrantyTitle': "સેવા વોરંટી",
        'serviceWarrantyDesc': "અમે અમારી સેવા માટે 7 દિવસની વોરંટી આપીએ છીએ.",
        'moreInfoBtn': "વધુ માહિતી",
        'shareServiceTitle': "સેવા શેર કરો",
        'shareServiceDesc': "તમારા મિત્રોને સહયોગસેવાની ભલામણ કરો.",
        'shareBtn': "શેર કરો",
        'afterServiceTitle': "સેવા પછી",
        'workSummaryTitle': "કામનો સારાંશ",
        'problemLabel': "સમસ્યા",
        'workDoneLabel': "કરેલું કામ",
        'actualDurationLabel': "લાગેલો સમય",
        'completionTimeLabel': "સેવા પૂર્ણ સમય",
        'paymentDetailsTitle': "ચુકવણી વિગત",
        'paymentMethodLabel': "ચુકવણી પદ્ધતિ",
        'paymentStatusLabel': "ચુકવણી સ્થિતિ",
        'invoiceNumberLabel': "રસીદ નંબર",
        'rateAndFeedbackBtn': "રેટિંગ અને પ્રતિસાદ આપો",
        'rateWorkerTitle': "રેટિંગ આપો",
        'howWasExperience': "તમારો અનુભવ કેવો રહ્યો?",
        'rateWorkerPrompt': "{name} ને રેટ કરો",
        'writeFeedbackHint': "તમારો પ્રતિભાવ લખો... (ઓછામાં ઓછા 10 શબ્દો)",
        'submitRatingBtn': "સબમિટ કરો",
        'step15ProceedToPayment': "ચુકવણી કરો ➔",
        'paymentModalTitle': "ચુકવણી કરો",
        'payNowBtn': "હવે ચુકવો",
        'ratingSubmittedSuccess': "આભાર! તમારું રેટિંગ સફળતાપૂર્વક સબમિટ થયું.",
        'ratingStar1': "નબળું",
        'ratingStar2': "સામાન્ય",
        'ratingStar3': "સારું",
        'ratingStar4': "ખૂબ સારું",
        'ratingStar5': "ઉત્કૃષ્ટ",
        'unitNos': "નંગ",
        'paymentProcessing': "ચુકવણી પ્રક્રિયા ચાલુ છે...",
        'ratingSubmitting': "રેટિંગ સબમિટ થઈ રહ્યું છે...",
        'invoiceDownloading': "PDF રસીદ ડાઉનલોડ થઈ રહી છે...",
        'invoiceDownloaded': "રસીદ સફળતાપૂર્વક ડાઉનલોડ થઈ!",
        'warrantyModalTitle': "7 દિવસની સેવા વોરંટી નીતિ",
        'warrantyModalContent': "સહયોગસેવા 7 દિવસ માટે ઉત્તમ ગુણવત્તાની ખાતરી આપે છે. જો કોઈ સમસ્યા થાય તો સહકારી કામદાર મફત સેવા આપશે.",
        'sampleProblemDesc': "નળમાંથી પાણી ટપકતું હતું.",
        'sampleWorkDoneDesc': "જોઇન્ટ રિપેર અને વોશર બદલ્યું.",
    },
    'ta': {
        'serviceCompletionTitle': "சேவை நிறைவு",
        'serviceCompletedTitle': "சேவை நிறைவடைந்தது!",
        'serviceCompletedSubtitle': "நன்றி! உங்கள் சேவை வெற்றிகரமாக முடிந்தது.",
        'serviceDetailsTitle': "சேவை விவரங்கள்",
        'dateTimeLabel': "தேதி மற்றும் நேரம்",
        'addressLabel': "முகவரி",
        'totalAmountLabel': "மொத்த கட்டணம்",
        'viewBreakdownBtn': "விவரங்களைப் பார்க்கவும்",
        'beforeAfterPhotosTitle': "வேலை புகைப்படங்கள் (முன் / பின்)",
        'beforeTag': "முன்",
        'afterTag': "பின்",
        'proceedToPaymentBtn': "கட்டணம் செலுத்தவும் ➔",
        'rateExperienceBtn': "அனுபவத்தை மதிப்பிடவும்",
        'downloadInvoiceBtn': "ரசீதை பதிவிறக்கவும்",
        'billSummaryTitle': "பில் சுருக்கம்",
        'baseAmountLabel': "அடிப்படைத் தொகை",
        'materialsCostLabel': "பொருட்கள் கட்டணம்",
        'serviceFeeLabel': "சேவைக் கட்டணம்",
        'discountLabel': "தள்ளுபடி",
        'paymentInfoTitle': "கட்டண விவரம்",
        'paymentSuccessfulBadge': "கட்டணம் வெற்றிகரமானது",
        'paymentPendingBadge': "கட்டணம் நிலுவையில் உள்ளது",
        'txnIdLabel': "பரிவர்த்தனை ஐடி",
        'dateLabel': "தேதி",
        'materialsUsedTitle': "பயன்படுத்தப்பட்ட பொருட்கள்",
        'materialsIncludedNote': "பொருட்கள் கட்டணத்தில் சேர்க்கப்பட்டுள்ளது.",
        'serviceDurationTitle': "சேவை காலம்",
        'totalDurationLabel': "மொத்த காலம்",
        'startTimeLabel': "தொடக்கம்",
        'endTimeLabel': "முடிவு",
        'rebookTileTitle': "மீண்டும் முன்பதிவு செய்க",
        'rebookTileDesc': "இந்த சேவை மீண்டும் தேவையா? ஒரு தட்டலில் முன்பதிவு செய்யுங்கள்.",
        'rebookWithWorkerDesc': "மீண்டும் சேவை தேவையா? ராகுல் சர்மாவுடன் மீண்டும் முன்பதிவு செய்யவும்.",
        'invoiceTileTitle': "விலைப்பட்டியல் / ரசீது",
        'invoiceTileDesc': "PDF ரசீதை பதிவிறக்கம் செய்து பகிரவும்.",
        'helpTileTitle': "உதவி தேவையா?",
        'helpTileDesc': "ஏதேனும் சிக்கல்கள் இருந்தால் உதவ தயாராக உள்ளோம்.",
        'contactBtn': "தொடர்பு கொள்ளவும்",
        'serviceWarrantyTitle': "சேவை உத்தரவாதம்",
        'serviceWarrantyDesc': "நாங்கள் 7 நாட்கள் சேவை உத்தரவாதம் வழங்குகிறோம்.",
        'moreInfoBtn': "கூடுதல் தகவல்",
        'shareServiceTitle': "சேவையை பகிரவும்",
        'shareServiceDesc': "உங்கள் நண்பர்களுக்கு SahayogSeva வை பரிந்துரைக்கவும்.",
        'shareBtn': "பகிர்",
        'afterServiceTitle': "சேவைக்கு பின்",
        'workSummaryTitle': "வேலை சுருக்கம்",
        'problemLabel': "பிரச்சினை",
        'workDoneLabel': "செய்யப்பட்ட வேலை",
        'actualDurationLabel': "எடுத்துக்கொண்ட நேரம்",
        'completionTimeLabel': "சேவை முடிந்த நேரம்",
        'paymentDetailsTitle': "கட்டண விவரங்கள்",
        'paymentMethodLabel': "கட்டண முறை",
        'paymentStatusLabel': "கட்டண நிலை",
        'invoiceNumberLabel': "ரசீது எண்",
        'rateAndFeedbackBtn': "மதிப்பீடு மற்றும் கருத்து வழங்கவும்",
        'rateWorkerTitle': "மதிப்பீடு அளிக்கவும்",
        'howWasExperience': "உங்கள் அனுபவம் எப்படி இருந்தது?",
        'rateWorkerPrompt': "{name} க்கு மதிப்பீடு அளிக்கவும்",
        'writeFeedbackHint': "உங்கள் கருத்தை எழுதுங்கள்... (குறைந்தது 10 வார்த்தைகள்)",
        'submitRatingBtn': "சமர்ப்பிக்கவும்",
        'step15ProceedToPayment': "கட்டணம் செலுத்தவும் ➔",
        'paymentModalTitle': "கட்டணம் செலுத்துங்கள்",
        'payNowBtn': "இப்போது செலுத்தவும்",
        'ratingSubmittedSuccess': "நன்றி! உங்கள் மதிப்பீடு வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது.",
        'ratingStar1': "மோசம்",
        'ratingStar2': "சுமார்",
        'ratingStar3': "நன்று",
        'ratingStar4': "மிக நன்று",
        'ratingStar5': "சிறப்பானது",
        'unitNos': "எண்ணிக்கை",
        'paymentProcessing': "கட்டணம் செயலாக்கப்படுகிறது...",
        'ratingSubmitting': "மதிப்பீடு சமர்ப்பிக்கப்படுகிறது...",
        'invoiceDownloading': "PDF ரசீது பதிவிறக்கப்படுகிறது...",
        'invoiceDownloaded': "ரசீது வெற்றிகரமாக பதிவிறக்கப்பட்டது!",
        'warrantyModalTitle': "7 நாள் சேவை உத்தரவாதக் கொள்கை",
        'warrantyModalContent': "SahayogSeva 7 நாட்கள் உத்தரவாதத்தை உறுதி செய்கிறது. 7 நாட்களுக்குள் சிக்கல் மீண்டும் ஏற்பட்டால் கூட்டுறவு பணியாளர் இலவசமாக சரிசெய்வார்.",
        'sampleProblemDesc': "குழாயில் தண்ணீர் கசிந்தது.",
        'sampleWorkDoneDesc': "இணைப்பு சரிசெய்யப்பட்டு வாஷர் மாற்றப்பட்டது.",
    },
    'te': {
        'serviceCompletionTitle': "సేవ పూర్తి",
        'serviceCompletedTitle': "సేవ పూర్తయింది!",
        'serviceCompletedSubtitle': "ధన్యవాదాలు! మీ సేవ విజయవంతంగా పూర్తయింది.",
        'serviceDetailsTitle': "సేవా వివరాలు",
        'dateTimeLabel': "తేదీ & సమయం",
        'addressLabel': "చిరునామా",
        'totalAmountLabel': "మొత్తం ఖర్చు",
        'viewBreakdownBtn': "వివరాలను చూడండి",
        'beforeAfterPhotosTitle': "పని ఫోటోలు (ముందు / తర్వాత)",
        'beforeTag': "ముందు",
        'afterTag': "తర్వాత",
        'proceedToPaymentBtn': "చెల్లింపు చేయండి ➔",
        'rateExperienceBtn': "అనుభవాన్ని రేట్ చేయండి",
        'downloadInvoiceBtn': "రసీదును డౌన్‌లోడ్ చేయండి",
        'billSummaryTitle': "బిల్లు సారాంశం",
        'baseAmountLabel': "ప్రాథమిక మొత్తం",
        'materialsCostLabel': "సామగ్రి ఖర్చు",
        'serviceFeeLabel': "సేవా రుసుము",
        'discountLabel': "రాయితీ",
        'paymentInfoTitle': "చెల్లింపు సమాచారం",
        'paymentSuccessfulBadge': "చెల్లింపు విజయవంతమైంది",
        'paymentPendingBadge': "చెల్లింపు పెండింగ్‌లో ఉంది",
        'txnIdLabel': "లావాదేవీ ఐడీ",
        'dateLabel': "తేదీ",
        'materialsUsedTitle': "ఉపయోగించిన సామగ్రి",
        'materialsIncludedNote': "సామగ్రి ఖర్చులో చేర్చబడింది.",
        'serviceDurationTitle': "సేవ వ్యవధి",
        'totalDurationLabel': "మొత్తం వ్యవధి",
        'startTimeLabel': "ప్రారంభం",
        'endTimeLabel': "ముగింపు",
        'rebookTileTitle': "మళ్లీ బుక్ చేయండి",
        'rebookTileDesc': "ఈ సేవ మళ్లీ కావాలా? ఒక్క ట్యాప్‌తో మళ్లీ బుక్ చేయండి.",
        'rebookWithWorkerDesc': "మళ్లీ సేవ కావాలా? రాహుల్ శర్మతో మళ్లీ బుక్ చేయండి.",
        'invoiceTileTitle': "ఇన్‌వాయిస్ / రసీదు",
        'invoiceTileDesc': "PDF రసీదును డౌన్‌లోడ్ చేసి షేర్ చేయండి.",
        'helpTileTitle': "సహాయం కావాలా?",
        'helpTileDesc': "ఏదైనా సమస్య ఉంటే మేము సహాయం చేయడానికి సిద్ధంగా ఉన్నాము.",
        'contactBtn': "సంప్రదించండి",
        'serviceWarrantyTitle': "సేవా వారంటీ",
        'serviceWarrantyDesc': "మేము మా సేవకు 7 రోజుల వారంటీని అందిస్తాము.",
        'moreInfoBtn': "మరింత సమాచారం",
        'shareServiceTitle': "సేవను పంచుకోండి",
        'shareServiceDesc': "మీ స్నేహితులకు SahayogSeva ను సిఫార్సు చేయండి.",
        'shareBtn': "షేర్ చేయండి",
        'afterServiceTitle': "సేవ తర్వాత",
        'workSummaryTitle': "పని సారాంశం",
        'problemLabel': "సమస్య",
        'workDoneLabel': "చేసిన పని",
        'actualDurationLabel': "పట్టిన సమయం",
        'completionTimeLabel': "సేవ పూర్తయిన సమయం",
        'paymentDetailsTitle': "చెల్లింపు వివరాలు",
        'paymentMethodLabel': "చెల్లింపు విధానం",
        'paymentStatusLabel': "చెల్లింపు స్థితి",
        'invoiceNumberLabel': "రసీదు సంఖ్య",
        'rateAndFeedbackBtn': "రేటింగ్ & అభిప్రాయం ఇవ్వండి",
        'rateWorkerTitle': "రేటింగ్ ఇవ్వండి",
        'howWasExperience': "మీ అనుభవం ఎలా ఉంది?",
        'rateWorkerPrompt': "{name} కు రేటింగ్ ఇవ్వండి",
        'writeFeedbackHint': "మీ అభిప్రాయాన్ని రాయండి... (కనీసం 10 పదాలు)",
        'submitRatingBtn': "సమర్పించండి",
        'step15ProceedToPayment': "చెల్లింపు చేయండి ➔",
        'paymentModalTitle': "చెల్లింపు చేయండి",
        'payNowBtn': "ఇప్పుడే చెల్లించండి",
        'ratingSubmittedSuccess': "ధన్యవాదాలు! మీ రేటింగ్ విజయవంతంగా సమర్పించబడింది.",
        'ratingStar1': "బాగాలేదు",
        'ratingStar2': "పర్వాలేదు",
        'ratingStar3': "బాగుంది",
        'ratingStar4': "చాలా బాగుంది",
        'ratingStar5': "అద్భుతం",
        'unitNos': "నెంబర్లు",
        'paymentProcessing': "చెల్లింపు ప్రాసెస్ అవుతోంది...",
        'ratingSubmitting': "రేటింగ్ సమర్పిస్తోంది...",
        'invoiceDownloading': "PDF రసీదు డౌన్‌లోడ్ అవుతోంది...",
        'invoiceDownloaded': "రసీదు విజయవంతంగా డౌన్‌లోడ్ అయింది!",
        'warrantyModalTitle': "7 రోజుల సేవా వారంటీ విధానం",
        'warrantyModalContent': "SahayogSeva 7 రోజుల పని నాణ్యత హామీని ఇస్తుంది. సమస్య మళ్లీ వస్తే సహకార కార్మికుడు ఉచితంగా పరిష్కరిస్తాడు.",
        'sampleProblemDesc': "పైపు నుండి నీరు లీక్ అవుతోంది.",
        'sampleWorkDoneDesc': "జాయింట్ రిపేర్ చేయబడింది మరియు వాషర్ మార్చబడింది.",
    },
    'kn': {
        'serviceCompletionTitle': "ಸೇವೆ ಪೂರ್ಣಗೊಂಡಿದೆ",
        'serviceCompletedTitle': "ಸೇವೆ ಪೂರ್ಣಗೊಂಡಿದೆ!",
        'serviceCompletedSubtitle': "ಧನ್ಯವಾದಗಳು! ನಿಮ್ಮ ಸೇವೆ ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಂಡಿದೆ.",
        'serviceDetailsTitle': "ಸೇವಾ ವಿವರಗಳು",
        'dateTimeLabel': "ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
        'addressLabel': "ವಿಳಾಸ",
        'totalAmountLabel': "ಒಟ್ಟು ವೆಚ್ಚ",
        'viewBreakdownBtn': "ವಿವರಗಳನ್ನು ನೋಡಿ",
        'beforeAfterPhotosTitle': "ಕೆಲಸದ ಫೋಟೋಗಳು (ಮೊದಲು / ನಂತರ)",
        'beforeTag': "ಮೊದಲು",
        'afterTag': "ನಂತರ",
        'proceedToPaymentBtn': "ಪಾವತಿ ಮಾಡಿ ➔",
        'rateExperienceBtn': "ಅನುಭವವನ್ನು ರೇಟ್ ಮಾಡಿ",
        'downloadInvoiceBtn': "ರಸೀದಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
        'billSummaryTitle': "ಬಿಲ್ ಸಾರಾಂಶ",
        'baseAmountLabel': "ಮೂಲ ಮೊತ್ತ",
        'materialsCostLabel': "ಸಾಮಗ್ರಿ ವೆಚ್ಚ",
        'serviceFeeLabel': "ಸೇವಾ ಶುಲ್ಕ",
        'discountLabel': "ರಿಯಾಯಿತಿ",
        'paymentInfoTitle': "ಪಾವತಿ ಮಾಹಿತಿ",
        'paymentSuccessfulBadge': "ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ",
        'paymentPendingBadge': "ಪಾವತಿ ಬಾಕಿ ಇದೆ",
        'txnIdLabel': "ವಹಿವಾಟು ಐಡಿ",
        'dateLabel': "ದಿನಾಂಕ",
        'materialsUsedTitle': "ಬಳಸಿದ ಸಾಮಗ್ರಿಗಳು",
        'materialsIncludedNote': "ಸಾಮಗ್ರಿ ವೆಚ್ಚದಲ್ಲಿ ಸೇರಿಸಲಾಗಿದೆ.",
        'serviceDurationTitle': "ಸೇವಾ ಅವಧಿ",
        'totalDurationLabel': "ಒಟ್ಟು ಅವಧಿ",
        'startTimeLabel': "ಪ್ರಾರಂಭ",
        'endTimeLabel': "ಅಂತ್ಯ",
        'rebookTileTitle': "ಮತ್ತೆ ಬುಕ್ ಮಾಡಿ",
        'rebookTileDesc': "ಈ ಸೇವೆ ಮತ್ತೆ ಬೇಕೇ? ಒಂದು ಟ್ಯಾಪ್‌ನಲ್ಲಿ ಮತ್ತೆ ಬುಕ್ ಮಾಡಿ.",
        'rebookWithWorkerDesc': "ಮತ್ತೆ ಸೇವೆ ಬೇಕೇ? ರಾಹುಲ್ ಶರ್ಮಾ ಅವರೊಂದಿಗೆ ಮತ್ತೆ ಬುಕ್ ಮಾಡಿ.",
        'invoiceTileTitle': "ಇನ್‌ವಾಯ್ಸ್ / ರಸೀದಿ",
        'invoiceTileDesc': "PDF ರಸೀದಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಹಂಚಿಕೊಳ್ಳಿ.",
        'helpTileTitle': "ಸಹಾಯ ಬೇಕೇ?",
        'helpTileDesc': "ಯಾವುದೇ ಸಮಸ್ಯೆ ಇದ್ದರೆ ನಾವು ಸಹಾಯ ಮಾಡಲು ಸಿದ್ಧರಿದ್ದೇವೆ.",
        'contactBtn': "ಸಂಪರ್ಕಿಸಿ",
        'serviceWarrantyTitle': "ಸೇವಾ ಖಾತರಿ",
        'serviceWarrantyDesc': "ನಾವು ನಮ್ಮ ಸೇವೆಗೆ 7 ದಿನಗಳ ಖಾತರಿ ನೀಡುತ್ತೇವೆ.",
        'moreInfoBtn': "ಹೆಚ್ಚಿನ ಮಾಹಿತಿ",
        'shareServiceTitle': "ಸೇವೆಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ",
        'shareServiceDesc': "ನಿಮ್ಮ ಸ್ನೇಹಿತರಿಗೆ SahayogSeva ಅನ್ನು ಶಿಫಾರಸು ಮಾಡಿ.",
        'shareBtn': "ಹಂಚಿಕೊಳ್ಳಿ",
        'afterServiceTitle': "ಸೇವೆಯ ನಂತರ",
        'workSummaryTitle': "ಕೆಲಸದ ಸಾರಾಂಶ",
        'problemLabel': "ಸಮಸ್ಯೆ",
        'workDoneLabel': "ಮಾಡಿದ ಕೆಲಸ",
        'actualDurationLabel': "ತೆಗೆದುಕೊಂಡ ಸಮಯ",
        'completionTimeLabel': "ಸೇವೆ ಪೂರ್ಣಗೊಂಡ ಸಮಯ",
        'paymentDetailsTitle': "ಪಾವತಿ ವಿವರಗಳು",
        'paymentMethodLabel': "ಪಾವತಿ ವಿಧಾನ",
        'paymentStatusLabel': "ಪಾವತಿ ಸ್ಥಿತಿ",
        'invoiceNumberLabel': "ರಸೀದಿ ಸಂಖ್ಯೆ",
        'rateAndFeedbackBtn': "ರೇಟಿಂಗ್ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆ ನೀಡಿ",
        'rateWorkerTitle': "ರೇಟಿಂಗ್ ನೀಡಿ",
        'howWasExperience': "ನಿಮ್ಮ ಅನುಭವ ಹೇಗಿತ್ತು?",
        'rateWorkerPrompt': "{name} ಅವರಿಗೆ ರೇಟಿಂಗ್ ನೀಡಿ",
        'writeFeedbackHint': "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಬರೆಯಿರಿ... (ಕನಿಷ್ಠ 10 ಪದಗಳು)",
        'submitRatingBtn': "ಸಲ್ಲಿಸಿ",
        'step15ProceedToPayment': "ಪಾವತಿ ಮಾಡಿ ➔",
        'paymentModalTitle': "ಪಾವತಿ ಮಾಡಿ",
        'payNowBtn': "ಈಗ ಪಾವತಿಸಿ",
        'ratingSubmittedSuccess': "ಧನ್ಯವಾದಗಳು! ನಿಮ್ಮ ರೇಟಿಂಗ್ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಕೆಯಾಗಿದೆ.",
        'ratingStar1': "ಕಳಪೆ",
        'ratingStar2': "ಸಾಧಾರಣ",
        'ratingStar3': "ಉತ್ತಮ",
        'ratingStar4': "ತುಂಬಾ ಉತ್ತಮ",
        'ratingStar5': "ಅತ್ಯುತ್ತಮ",
        'unitNos': "ಸಂಖ್ಯೆ",
        'paymentProcessing': "ಪಾವತಿ ಪ್ರಕ್ರಿಯೆ ನಡೆಯುತ್ತಿದೆ...",
        'ratingSubmitting': "ರೇಟಿಂಗ್ ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
        'invoiceDownloading': "PDF ರಸೀದಿ ಡೌನ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
        'invoiceDownloaded': "ರಸೀದಿ ಯಶಸ್ವಿಯಾಗಿ ಡೌನ್‌ಲೋಡ್ ಆಗಿದೆ!",
        'warrantyModalTitle': "7 ದಿನಗಳ ಸೇವಾ ಖಾತರಿ ನೀತಿ",
        'warrantyModalContent': "SahayogSeva 7 ದಿನಗಳ ಕೆಲಸದ ಗುಣಮಟ್ಟದ ಭರವಸೆಯನ್ನು ನೀಡುತ್ತದೆ. ಸಮಸ್ಯೆ ಮತ್ತೆ ಬಂದರೆ ಸಹಕಾರಿ ಕೆಲಸಗಾರ ಉಚಿತವಾಗಿ ಸರಿಪಡಿಸುತ್ತಾನೆ.",
        'sampleProblemDesc': "ನಲ್ಲಿಯಿಂದ ನೀರು ಸೋರುತ್ತಿತ್ತು.",
        'sampleWorkDoneDesc': "ಜಾಯಿಂಟ್ ದುರಸ್ತಿ ಮಾಡಲಾಯಿತು ಮತ್ತು ವಾಷರ್ ಬದಲಾಯಿಸಲಾಯಿತು.",
    },
    'bn': {
        'serviceCompletionTitle': "পরিষেবা সমাপ্তি",
        'serviceCompletedTitle': "পরিষেবা সম্পন্ন হয়েছে!",
        'serviceCompletedSubtitle': "ধন্যবাদ! আপনার পরিষেবা সফলভাবে সম্পন্ন হয়েছে।",
        'serviceDetailsTitle': "পরিষেবার বিবরণ",
        'dateTimeLabel': "তারিখ ও সময়",
        'addressLabel': "ঠিকানা",
        'totalAmountLabel': "মোট খরচ",
        'viewBreakdownBtn': "বিবরণ দেখুন",
        'beforeAfterPhotosTitle': "কাজের ছবি (আগে / পরে)",
        'beforeTag': "আগে",
        'afterTag': "পরে",
        'proceedToPaymentBtn': "পেমেন্ট করুন ➔",
        'rateExperienceBtn': "অভিজ্ঞতা রেটিং দিন",
        'downloadInvoiceBtn': "রসিদ ডাউনলোড করুন",
        'billSummaryTitle': "বিল সারাংশ",
        'baseAmountLabel': "মূল পরিমাণ",
        'materialsCostLabel': "উপকরণ খরচ",
        'serviceFeeLabel': "পরিষেবা ফি",
        'discountLabel': "ছাড়",
        'paymentInfoTitle': "পেমেন্ট তথ্য",
        'paymentSuccessfulBadge': "পেমেন্ট সফল",
        'paymentPendingBadge': "পেমেন্ট বাকি আছে",
        'txnIdLabel': "লেনদেন আইডি",
        'dateLabel': "তারিখ",
        'materialsUsedTitle': "ব্যবহৃত উপকরণ",
        'materialsIncludedNote': "উপকরণ খরচে অন্তর্ভুক্ত।",
        'serviceDurationTitle': "পরিষেবা সময়কাল",
        'totalDurationLabel': "মোট সময়কাল",
        'startTimeLabel': "শুরু",
        'endTimeLabel': "সমাপ্ত",
        'rebookTileTitle': "আবার বুক করুন",
        'rebookTileDesc': "এই পরিষেবা আবার প্রয়োজন? এক ট্যাপে বুক করুন।",
        'rebookWithWorkerDesc': "আবার পরিষেবা প্রয়োজন? রাহুল শর্মার সাথে আবার বুক করুন।",
        'invoiceTileTitle': "চালান / রসিদ",
        'invoiceTileDesc': "PDF রসিদ ডাউনলোড করুন এবং শেয়ার করুন।",
        'helpTileTitle': "সাহায্য প্রয়োজন?",
        'helpTileDesc': "কোনো সমস্যা থাকলে আমরা সাহায্য করতে প্রস্তুত।",
        'contactBtn': "যোগাযোগ করুন",
        'serviceWarrantyTitle': "পরিষেবা ওয়্যারেন্টি",
        'serviceWarrantyDesc': "আমরা আমাদের পরিষেবার জন্য ৭ দিনের ওয়ারেন্টি প্রদান করি।",
        'moreInfoBtn': "আরও তথ্য",
        'shareServiceTitle': "পরিষেবা শেয়ার করুন",
        'shareServiceDesc': "আপনার বন্ধুদের SahayogSeva সুপারিশ করুন।",
        'shareBtn': "শেয়ার করুন",
        'afterServiceTitle': "পরিষেবার পরে",
        'workSummaryTitle': "কাজের সারাংশ",
        'problemLabel': "সমস্যা",
        'workDoneLabel': "সম্পন্ন কাজ",
        'actualDurationLabel': "প্রকৃত সময়",
        'completionTimeLabel': "পরিষেবা সমাপ্তির সময়",
        'paymentDetailsTitle': "পেমেন্ট বিবরণ",
        'paymentMethodLabel': "পেমেন্ট পদ্ধতি",
        'paymentStatusLabel': "পেমেন্ট স্থিতি",
        'invoiceNumberLabel': "রসিদ নম্বর",
        'rateAndFeedbackBtn': "রেটিং ও মতামত দিন",
        'rateWorkerTitle': "রেটিং দিন",
        'howWasExperience': "আপনার অভিজ্ঞতা কেমন ছিল?",
        'rateWorkerPrompt': "{name}-কে রেটিং দিন",
        'writeFeedbackHint': "আপনার মতামত লিখুন... (ন্যূনতম ১০ শব্দ)",
        'submitRatingBtn': "জমা দিন",
        'step15ProceedToPayment': "পেমেন্ট করুন ➔",
        'paymentModalTitle': "পেমেন্ট সম্পন্ন করুন",
        'payNowBtn': "এখন পেমেন্ট করুন",
        'ratingSubmittedSuccess': "ধন্যবাদ! আপনার রেটিং সফলভাবে জমা হয়েছে।",
        'ratingStar1': "খারাপ",
        'ratingStar2': "মোটামুটি",
        'ratingStar3': "ভালো",
        'ratingStar4': "খুব ভালো",
        'ratingStar5': "চমৎকার",
        'unitNos': "টি",
        'paymentProcessing': "পেমেন্ট প্রক্রিয়া চলছে...",
        'ratingSubmitting': "রেটিং জমা হচ্ছে...",
        'invoiceDownloading': "PDF রসিদ ডাউনলোড হচ্ছে...",
        'invoiceDownloaded': "রসিদ সফলভাবে ডাউনলোড হয়েছে!",
        'warrantyModalTitle': "৭ দিনের পরিষেবা ওয়্যারেন্টি নীতি",
        'warrantyModalContent': "SahayogSeva ৭ দিনের কাজের মানের নিশ্চয়তা দেয়। ৭ দিনের মধ্যে সমস্যা পুনরায় দেখা দিলে সমবায় কর্মী বিনামূল্যে মেরামত করবেন।",
        'sampleProblemDesc': "কল থেকে জল পড়ছিল।",
        'sampleWorkDoneDesc': "জয়েন্ট মেরামত করা হয়েছে এবং ওয়াশার পরিবর্তন করা হয়েছে।",
    }
}

for lang, kv in translations.items():
    search_target = f"'{lang}': {{"
    pos = content.find(search_target)
    if pos != -1:
        # Find where this language map ends
        # We can look for the next language map or closing bracket
        # Let's find 'noTrackingDataFound' in this section
        target_str = "'noTrackingDataFound':"
        sub_pos = content.find(target_str, pos)
        if sub_pos != -1:
            line_end = content.find('\n', sub_pos)
            to_insert = ""
            for k, v in kv.items():
                # Escape quotes if needed
                v_clean = v.replace('"', '\\"')
                to_insert += f"\n    '{k}': \"{v_clean}\","
            content = content[:line_end] + to_insert + content[line_end:]

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Successfully injected all Step 16 and Step 17 localization keys across all 8 languages!")
