// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-pfJ-Iboq0q1eszE4SXZ98E6YTbAdhnU',
    appId: '1:923684572302:web:ed3fd971ca0c8569694ddf',
    messagingSenderId: '923684572302',
    projectId: 'sahayogseva-789ea',
    authDomain: 'sahayogseva-789ea.firebaseapp.com',
    storageBucket: 'sahayogseva-789ea.firebasestorage.app',
    measurementId: 'G-8MMQ2FMJMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQOu3COAqZLFrj_yL8AHkOQHdBLObOndI',
    appId: '1:923684572302:android:d4e66e21dd41dc58694ddf',
    messagingSenderId: '923684572302',
    projectId: 'sahayogseva-789ea',
    storageBucket: 'sahayogseva-789ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE8yvG1wBx6uJ9Wf1who35gDocAx4EiTQ',
    appId: '1:923684572302:ios:1027ffc83edc82e8694ddf',
    messagingSenderId: '923684572302',
    projectId: 'sahayogseva-789ea',
    storageBucket: 'sahayogseva-789ea.firebasestorage.app',
    iosBundleId: 'com.sahayogseva.sahayogseva',
  );
}
